version: "2"
run:
  concurrency: 8
  modules-download-mode: mod
  tests: true
linters:
  default: all
  disable:
    - cyclop
    - funlen
    - gocognit
    - gocyclo
    - gomoddirectives
    - misspell
    - varnamelen
    - wsl
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          allow:
            - $gostd
            - github.com/keboola/terraform-provider-keboola
    exhaustive:
      default-signifies-exhaustive: true
    forbidigo:
      forbid:
        - pattern: ^(fmt\.Print.*|print|println)$
          msg: Debug statements are forbidden, use a logger, not debug statements.
        - pattern: ^os\.(Setenv|Getenv|Unsetenv|Lookupenv|Clearenv|PathSeparator)$
          msg: Os ENVs singleton is forbidden, use env.Map instead.
        - pattern: ^os\.(Stdout|Stderr)$
          msg: Use dependencies instead.
      analyze-types: true
    gocyclo:
      min-complexity: 10
    wrapcheck:
      ignore-package-globs:
        - github.com/keboola/terraform-provider-keboola/*
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - forbidigo
        path: cmd/main.go
        text: use of `os.Std(out|err)` forbidden
      - linters:
          - exhaustruct
          - lll
          - wrapcheck
        path: .*_test.go
      - linters:
          - exhaustruct
        path: provider.go
      - linters:
          - exhaustruct
        path: internal/providermodels/
      - linters:
          - exhaustruct
        path: internal/provider/resources/.*/mapper.go
      - linters:
          - exhaustruct
        path: internal/provider/resources/.*/resource.go
      - path: (.+)\.go$
        text: variable name 'tc' is too short for the scope of its usage
      - path: (.+)\.go$
        text: 'G306: Expect WriteFile permissions to be 0600 or less'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
