package configuration

import (
	"context"
	"fmt"
	"os"
	"strconv"
	"strings"
	"github.com/hashicorp/terraform-plugin-framework/path"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/keboola/keboola-sdk-go/v2/pkg/keboola"

	"github.com/keboola/terraform-provider-keboola/internal/provider/abstraction"
	"github.com/keboola/terraform-provider-keboola/internal/providermodels"
)

// Ensure the implementation satisfies the expected interfaces.
var (
	_ resource.ResourceWithImportState = &Resource{}
	_ resource.Resource = &Resource{
		base:   abstraction.BaseResource[ConfigModel, *keboola.ConfigWithRows]{},
		client: nil,
		isTest: false,
	}
	_ resource.ResourceWithConfigure = &Resource{
		base:   abstraction.BaseResource[ConfigModel, *keboola.ConfigWithRows]{},
		client: nil,
		isTest: false,
	}
)

// Resource is the configuration resource implementation.
type Resource struct {
	// Base functionality with config model specifics
	base abstraction.BaseResource[ConfigModel, *keboola.ConfigWithRows]

	// Direct access to the API client for specific operations
	client *keboola.AuthorizedAPI
	isTest bool

	// List of components available in the project, fetched during provider configuration.
	// This is used to validate the component_id provided in the resource configuration.
	availableComponents []*keboola.Component
}

// NewResource is a helper function to simplify the provider implementation.
func NewResource() *Resource {
	return &Resource{
		base:   abstraction.BaseResource[ConfigModel, *keboola.ConfigWithRows]{},
		client: nil,
		isTest: false,
	}
}

// Metadata returns the resource type name.
func (r *Resource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_component_configuration"
}

// Schema defines the schema for the resource.
func (r *Resource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description:         "Manages component configurations (https://keboola.docs.apiary.io/#reference/components-and-configurations).", //nolint: lll
		MarkdownDescription: "Manages component configurations (https://keboola.docs.apiary.io/#reference/components-and-configurations).", //nolint: lll
		Blocks:              map[string]schema.Block{},
		DeprecationMessage:  "",
		Version:             1,
		Attributes: map[string]schema.Attribute{
			// 'id' is the unique configuration identifier.
			"id": schema.StringAttribute{
				Description:         "ID of the configuration. If not specified, then will be autogenerated.",
				MarkdownDescription: "ID of the configuration. If not specified, then will be autogenerated.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
					// Custom plan modifier to force resource replacement if id changes.
					forceNewIfIDChangesModifier{},
				},
			},
			"branch_id": schema.StringAttribute{
				Description:         "ID of the branch. If not specified, then default branch will be used.",
				MarkdownDescription: "ID of the branch. If not specified, then default branch will be used.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"component_id": schema.StringAttribute{
				Description:         "ID of the component.",
				MarkdownDescription: "ID of the component.",
				Required:            true,
			},
			"name": schema.StringAttribute{
				Description: "Name of the configuration.",
				Required:    true,
			},
			"description": schema.StringAttribute{
				Description: "Description of the configuration.",
				Optional:    true,
				Computed:    true,
			},
			"change_description": schema.StringAttribute{
				Description: "Change description associated with the configuration change.",
				Optional:    true,
				Computed:    true,
			},
			"is_disabled": schema.BoolAttribute{
				Description: "Whether configuration is enabled or disabled.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
				},
			},
			"configuration": schema.StringAttribute{
				Description: "Content of the configuration specified as JSON string.",
				Optional:    true,
				Computed:    true,
			},
			"is_deleted": schema.BoolAttribute{
				Description: "Whether configuration has been deleted or not.",
				Computed:    true,
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
				},
			},
			"created": schema.StringAttribute{
				Description: "Timestamp of the configuration creation date.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"fqn": schema.StringAttribute{
				Description: "Fully qualified name for the configuration, composed as branch_id/component_id/configuration_id.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"rows": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Description: "ID of the configuration row",
							Computed:    true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
							},
						},
						"name": schema.StringAttribute{
							Description: "Name of the configuration row.",
							Required:    true,
						},
						"description": schema.StringAttribute{
							Description: "Description of the configuration row.",
							Optional:    true,
							Computed:    true,
						},
						"change_description": schema.StringAttribute{
							Description: "Change description associated with the configuration row change.",
							Optional:    true,
							Computed:    true,
						},
						"is_disabled": schema.BoolAttribute{
							Description: "Whether configuration row is enabled or disabled.",
							Optional:    true,
							Computed:    true,
							PlanModifiers: []planmodifier.Bool{
								boolplanmodifier.UseStateForUnknown(),
							},
						},
						"state": schema.StringAttribute{
							Description: "State of the configuration row.",
							Computed:    true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
							},
						},
						"configuration_row": schema.StringAttribute{
							Description: "Content of the configuration row specified as JSON string.",
							Optional:    true,
							Computed:    true,
						},
					},
				},
				Description: "Rows for the configuration",
				Optional:    true,
			},
		},
	}
}

// Configure adds the provider configured client to the resource.
func (r *Resource) Configure(
	_ context.Context,
	req resource.ConfigureRequest,
	_ *resource.ConfigureResponse,
) {
	// Return silently if provider data is not available (yet)
	if req.ProviderData == nil {
		return
	}

	// Get the provider data - ignoring the type assertion success
	providerData, _ := req.ProviderData.(*providermodels.ProviderData)
	r.client = providerData.Client
	// Store the fetched components from provider data for validation purposes.
	r.availableComponents = providerData.Components
	r.isTest = os.Getenv("TF_ACC") != "" //nolint: forbidigo

	// Set up the mapper
	r.base.Mapper = &ConfigMapper{
		RowHandler: &DefaultConfigRowHandler{
			Client: r.client,
			isTest: r.isTest,
		},
		isTest:              r.isTest,
		AvailableComponents: r.availableComponents,
	}
}

// Create creates the resource and sets the initial Terraform state.
func (r *Resource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	tflog.Info(ctx, "Creating configuration resource")

	// Use the base resource abstraction for Create
	r.base.ExecuteCreate(ctx, req, resp, func(ctx context.Context, plan ConfigModel) (*keboola.ConfigWithRows, error) {
		// Handle default branch if not specified
		if plan.BranchID.IsUnknown() {
			branch, err := r.client.GetDefaultBranchRequest().Send(ctx)
			if err != nil {
				return nil, fmt.Errorf("could not get default branch: %w", err)
			}

			plan.BranchID = types.StringValue(fmt.Sprintf("%d", branch.ID))
		}

		// Execute the create operation using the mapper
		apiModel, err := r.base.Mapper.MapTerraformToAPI(ctx, ConfigModel{}, plan)
		if err != nil {
			return nil, fmt.Errorf("failed to map Terraform model to API: %w", err)
		}

		// Create configuration via API
		resConfig, err := r.client.CreateConfigRequest(apiModel, false).Send(ctx)
		if err != nil {
			return nil, fmt.Errorf("could not create configuration: %w", err)
		}

		return resConfig, nil
	})
}

// Read resource information.
func (r *Resource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	tflog.Info(ctx, "Reading configuration resource")

	// Use the base resource abstraction for Read
	r.base.ExecuteRead(ctx, req, resp, func(ctx context.Context, state ConfigModel) (*keboola.ConfigWithRows, error) {
		// Create key from model
		branchID, err := strconv.ParseInt(state.BranchID.ValueString(), 10, 64)
		if err != nil {
			return nil, fmt.Errorf("invalid branch_id: %w", err)
		}

		key := keboola.ConfigKey{
			ID:          keboola.ConfigID(state.ID.ValueString()),
			BranchID:    keboola.BranchID(branchID),
			ComponentID: keboola.ComponentID(state.ComponentID.ValueString()),
		}

		// Get configuration
		config, err := r.client.GetConfigRequest(key).Send(ctx)
		if err != nil {
			return nil, fmt.Errorf("could not read Configuration %s: %w", state.ID.ValueString(), err)
		}

		// Get rows separately
		rowKey := keboola.ConfigRowKey{
			ConfigID:    key.ID,
			BranchID:    key.BranchID,
			ComponentID: key.ComponentID,
		}

		// Fetch rows from API
		rows, err := r.client.ListConfigRowRequest(rowKey).Send(ctx)
		if err != nil {
			return nil, fmt.Errorf("could not read configuration rows: %w", err)
		}

		// Prepare configuration with rows for mapping
		configWithRows := &keboola.ConfigWithRows{
			Config: config,
			Rows:   *rows,
		}

		return configWithRows, nil
	})
}

// Update updates the resource.
func (r *Resource) Update(
	ctx context.Context,
	req resource.UpdateRequest,
	resp *resource.UpdateResponse,
) {
	tflog.Info(ctx, "Updating configuration resource")

	// Use the base resource abstraction for Update
	r.base.ExecuteUpdate(
		ctx,
		req,
		resp,
		func(ctx context.Context, state, plan ConfigModel) (
			*keboola.ConfigWithRows,
			error,
		) {
			// Preserve branch, component, and config IDs from state
			plan.BranchID = state.BranchID
			plan.ComponentID = state.ComponentID
			plan.ID = state.ID

			// Execute the update operation using the mapper
			apiModel, err := r.base.Mapper.MapTerraformToAPI(ctx, state, plan)
			if err != nil {
				return nil, fmt.Errorf("failed to map Terraform model to API: %w", err)
			}

			tflog.Info(ctx, "Updating configuration", map[string]any{
				"rows_count": len(apiModel.Rows),
			})

			// Verbose logging: only appears in debug mode
			for _, row := range apiModel.Rows {
				tflog.Debug(ctx, "Updating configuration row", map[string]any{
					"configRowKey": row.ConfigRowKey,
				})
			}

			// Determine which fields to update based on rows presence and state changes
			changeFields := []string{
				"name",
				"description",
				"isDisabled",
				"changeDescription",
				"configuration",
			}

			// Get state row count for comparison
			stateRowCount := 0

			if !state.Rows.IsNull() && !state.Rows.IsUnknown() {
				var stateRows []any
				if diags := state.Rows.ElementsAs(ctx, &stateRows, false); !diags.HasError() {
					stateRowCount = len(stateRows)
				}
			}

			planRowCount := len(apiModel.Rows)

			tflog.Info(ctx, "Row count comparison", map[string]any{
				"state_row_count": stateRowCount,
				"plan_row_count":  planRowCount,
			})

			// Include rows and rowsSortOrder fields when:
			// 1. Plan has rows (rows are being added/modified)
			// 2. State had rows but plan has no rows (rows are being removed)
			if planRowCount > 0 || (stateRowCount > 0 && planRowCount == 0) {
				changeFields = append(changeFields, "rows")
			}

			resConfig, err := r.client.UpdateConfigRequest(apiModel, changeFields).Send(ctx)
			if err != nil {
				return nil, fmt.Errorf("could not update configuration: %w", err)
			}

			return resConfig, nil
		})
}

// Delete deletes the resource.
func (r *Resource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	tflog.Info(ctx, "Deleting configuration resource")

	// Use the base resource abstraction for Delete
	r.base.ExecuteDelete(ctx, req, resp, func(ctx context.Context, state ConfigModel) error {
		// Create key from model
		branchID, err := strconv.ParseInt(state.BranchID.ValueString(), 10, 64)
		if err != nil {
			return fmt.Errorf("invalid branch_id: %w", err)
		}

		key := keboola.ConfigKey{
			ID:          keboola.ConfigID(state.ID.ValueString()),
			BranchID:    keboola.BranchID(branchID),
			ComponentID: keboola.ComponentID(state.ComponentID.ValueString()),
		}

		// Delete the configuration
		err = r.client.DeleteConfigRequest(key).SendOrErr(ctx)
		if err != nil {
			return fmt.Errorf("could not delete configuration: %w", err)
		}

		return nil
	})
}

func (r *Resource) UpgradeState(ctx context.Context) map[int64]resource.StateUpgrader {
	tflog.Info(ctx, "Upgrading configuration resource state")

	// Upgrade the state
	return map[int64]resource.StateUpgrader{
		// State upgrade implementation from 0 (prior state version) to 2 (Schema.Version)
		0: {
			// Optionally, the PriorSchema field can be defined.
			StateUpgrader: func(ctx context.Context, req resource.UpgradeStateRequest, resp *resource.UpgradeStateResponse) {
				diags := resp.State.Set(ctx, req.State)
				resp.Diagnostics.Append(diags...)
			},
		},
		// State upgrade implementation from 1 (prior state version) to 2 (Schema.Version)
		1: {
			// Optionally, the PriorSchema field can be defined.
			StateUpgrader: func(ctx context.Context, req resource.UpgradeStateRequest, resp *resource.UpgradeStateResponse) {
				diags := resp.State.Set(ctx, req.State)
				resp.Diagnostics.Append(diags...)
			},
		},
	}
}

// forceNewIfIDChangesModifier is a custom plan modifier that forces resource replacement if the id changes.
// Note: 'ID' is capitalized as per Go initialism conventions.
type forceNewIfIDChangesModifier struct{}

func (m forceNewIfIDChangesModifier) Description(_ context.Context) string {
	return "Forces resource replacement if the id changes."
}

func (m forceNewIfIDChangesModifier) MarkdownDescription(_ context.Context) string {
	return "Forces resource replacement if the id changes."
}

func (m forceNewIfIDChangesModifier) PlanModifyString(
	_ context.Context,
	req planmodifier.StringRequest,
	resp *planmodifier.StringResponse,
) {
	if isStateOrPlanValueInvalid(req) {
		return
	}

	if req.StateValue.ValueString() != req.PlanValue.ValueString() {
		resp.RequiresReplace = true
	}
}

// isStateOrPlanValueInvalid checks if either the state or plan value is null or unknown.
// This helps to keep PlanModifyString logic clean and readable.
func isStateOrPlanValueInvalid(req planmodifier.StringRequest) bool {
	return req.StateValue.IsNull() || req.StateValue.IsUnknown() || req.PlanValue.IsNull() || req.PlanValue.IsUnknown()
}

// ImportState imports an existing configuration resource by compound ID.
// The import ID should be in format "branch_id/component_id/configuration_id" (e.g., "123/keboola.ex-db-mysql/12345").
// If branch_id is omitted, default branch will be used (e.g., "keboola.ex-db-mysql/12345").
func (r *Resource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	tflog.Info(ctx, "Importing configuration resource", map[string]any{
		"import_id": req.ID,
	})

	// Parse the import ID
	parts := strings.Split(req.ID, "/")

	var branchID, componentID, configID string

	switch len(parts) {
	case 2:
		// Format: component_id/configuration_id (use default branch)
		componentID = parts[0]
		configID = parts[1]
		// branchID will be set by provider default
	case 3:
		// Format: branch_id/component_id/configuration_id
		branchID = parts[0]
		componentID = parts[1]
		configID = parts[2]
	default:
		resp.Diagnostics.AddError(
			"Invalid Import ID Format",
			fmt.Sprintf("Expected import ID format: 'branch_id/component_id/configuration_id' or 'component_id/configuration_id', got: %s", req.ID),
		)
		return
	}

	// Set the parsed values in state
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), configID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("component_id"), componentID)...)

	if branchID != "" {
		resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("branch_id"), branchID)...)
	}

	tflog.Info(ctx, "Parsed import ID", map[string]any{
		"branch_id":    branchID,
		"component_id": componentID,
		"config_id":    configID,
	})
}
