name: "Acceptance tests"

on:
  push:
    # Avoid tags
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true
      - name: "run acceptance tests"
        env:
          TEST_KBC_HOST: "https://connection.north-europe.azure.keboola.com"
          TEST_KBC_TOKEN: ${{ secrets.TEST_KBC_TOKEN_AZ_NE_11122 }}
